# -*- coding: utf-8 -*-
"""step2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNI-UV6SIL0NFwy4GxShvvS9ZVTiiNhf

#Gerar tabela com os nomes das linhas e suas respectivas tarifas
"""

import pandas as pd
import requests
import xlsxwriter
import re
import urllib.request as ur
from unidecode import unidecode
from google.colab import drive
import time

drive.mount('/content/drive')

def remove_non_ascii(text):
    return unidecode(text)

def web_search(search_string):
    search_string = search_string.split(' ')
    search_string = '+'.join(search_string)
    yahoo_search = 'https://br.search.yahoo.com/search?p=' + search_string
    source = ur.urlopen(yahoo_search)
    source = source.read()
    source = str(source)
    output = re.findall(r'''(?:https://|www.)[^"]+''', source)
    results = []
    for i in range(len(output)):
        if 'moovitapp.com' in output[i]:
            results.append(output[i])
    return results

def find_tax(url):
    page = requests.get(url).text
    pos = page.find('R$')
    if pos != -1:
        raw = page[pos + 2:pos + 8].replace(',', '.').strip()
        tax = ''
        for c in raw:
            if c in '0123456789.':
                tax += c
        if tax != '' and tax[-1] in '0123456789':
            tax = tax
        else:
            tax = tax[:len(tax) - 1]
        if tax != '' and tax[0] == '0':
            tax = '0'
        if tax == '':
            tax = '0'
        return tax
    else:
        return '0'

path_ = '/content/drive/My Drive/Hawk/Trabalhos/WorkplaceOptimization/'

lines_file = path_ + 'results/linhas.xlsx'  # tabela com os nomes das linhas

lines_df = pd.read_excel(lines_file)

tax_dict = {}
search_counter = 0
for idx_l, plan_l in lines_df.iterrows():
    search_counter += 1
    query_ = plan_l['LINHA'] + ' R$ moovitapp'
    query_ = remove_non_ascii(query_)
    print(query_)
    tax_ = 0.0
    urls = web_search(query_)
    for url_ in urls:
        if 'pdf' in url_ or 'span' in url_:
            continue
        print(url_)
        tax_ = find_tax(url_)
        if tax_ != '0':
            break
        elif 'Linha' in plan_l['LINHA']:  # é metro
            tax_ = '4.40'
        time.sleep(20)
    tax_dict[plan_l['LINHA']] = float(tax_)
    print(search_counter)
    print(tax_)
    print('')
    if search_counter == 428:  # depois de muitas buscas, o moovit bloqueia as buscas
        search_counter = 0
        time.sleep(20)

workbook = xlsxwriter.Workbook(path_ + 'results/linhas_tarifas.xlsx')
worksheet = workbook.add_worksheet()
worksheet.write(0, 0, 'LINHA')
worksheet.write(0, 1, 'TARIFA')
row = 1
col = 0
keys = tax_dict.keys()
for key in keys:
    worksheet.write(row, col, key)
    worksheet.write(row, col + 1, tax_dict[key])
    row += 1
workbook.close()