# -*- coding: utf-8 -*-
"""step1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1DnEl-qtz8rHj9FDHJzu5p4jPpLKOik

# Gerar tabela com os nomes das linhas de transporte público utilizadas
"""

import pandas as pd
import googlemaps
import xlsxwriter
from datetime import datetime
from google.colab import drive

drive.mount('/content/drive')

path_ = '/content/drive/My Drive/Hawk/Trabalhos/WorkplaceOptimization/'

#                             |--------- Google Maps API key ---------|
gmaps = googlemaps.Client(key='AIzaSyD-cV9WbzfDeY1DTxsFifqOAT284wlW7Bs')

employees_file = path_ + 'data/Brasanitas_Tabela_Enderecos.xlsx'  # tabela com os endereços dos funcionários e dos seus locais de trabalho
branches_file = path_ + 'data/Brasanitas_Endereco_Filiais.xlsx'   # tabela com os endereços de todas a filiais

employees_df = pd.read_excel(employees_file)
branches_df = pd.read_excel(branches_file)

line_names = []

departure = datetime(2022, 10, 17, 7, 0)  # 17/10/2022 07h00
dep_ts = int(round(departure.timestamp()))

# ida
for idx_e, plan_e in employees_df.iterrows():
    origin = str(plan_e['Endereço']) + ', ' + str(plan_e['Num.Endereço']) + ', ' + str(plan_e['Bairro']) + ', ' + str(
        plan_e['Municipio']) + ', ' + str(plan_e['Estado']) + ', ' + plan_e['Cep']

    for idx_b, plan_b in branches_df.iterrows():
        destiny = plan_b['ENDERECO'] + ', ' + plan_b['BAIRRO'] + ', ' + plan_b['MUNICIPIO'] + ', ' + plan_b['ESTADO'] + ', ' + plan_b['CEP']

        try:
            directions_result = gmaps.directions(origin, destiny, mode='transit', departure_time=dep_ts)
            if len(directions_result) != 0:
                steps = directions_result[0]['legs'][0]['steps']

                for i in range(len(steps)):
                    if 'transit_details' in steps[i]:
                        line = steps[i]['transit_details']['line']
                        line_name = line['name']
                        if 'short_name' in line:
                            line_name = line['short_name'] + ' ' + line_name

                        isIncluded = False
                        for j in range(len(line_names)):
                            if line_name == line_names[j]:
                                isIncluded = True
                                break
                        if not isIncluded:
                            print(line_name)
                            line_names.append(line_name)
        except googlemaps.exceptions.ApiError:
            print("Not found")
            print('Origin:', origin)
            print('Destiny:', destiny)
            print('  ')

regress = datetime(2022, 10, 7, 17, 0)  # 22/09/2022 17h00
reg_ts = int(round(regress.timestamp()))

# volta
for idx_b, plan_b in branches_df.iterrows():
    origin = plan_b['ENDERECO'] + ', ' + plan_b['BAIRRO'] + ', ' + plan_b['MUNICIPIO'] + ', ' + plan_b['ESTADO'] + ', ' + plan_b['CEP']
    for idx_e, plan_e in employees_df.iterrows():
        destiny = str(plan_e['Endereço']) + ', ' + str(plan_e['Num.Endereço']) + ', ' + str(plan_e['Bairro']) + ', ' + str(plan_e['Municipio']) + ', ' + str(plan_e['Estado']) + ', ' + plan_e['Cep']
        try:
            directions_result = gmaps.directions(origin, destiny, mode='transit', departure_time=reg_ts)
            if len(directions_result) != 0:
                steps = directions_result[0]['legs'][0]['steps']

                for i in range(len(steps)):
                    if 'transit_details' in steps[i]:
                        line = steps[i]['transit_details']['line']
                        line_name = line['name']
                        if 'short_name' in line:
                            line_name = line['short_name'] + ' ' + line_name

                        isIncluded = False
                        for j in range(len(line_names)):
                            if line_name == line_names[j]:
                                isIncluded = True
                                break
                        if not isIncluded:
                            print(line_name)
                            line_names.append(line_name)
        except googlemaps.exceptions.ApiError:
            print("Not found")
            print('Origin:', origin)
            print('Destiny:', destiny)
            print('  ')

workbook = xlsxwriter.Workbook(path_ + 'results/linhas.xlsx')
worksheet = workbook.add_worksheet()
worksheet.write(0, 0, "LINHA")
for row in range(1, len(line_names) + 1):
    worksheet.write(row, 0, line_names[row - 1])
workbook.close()