# -*- coding: utf-8 -*-
"""step3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e7ZKuCMgbhssL-ciH4uf7FrvVRUZbNTO

#Gerar tabela com o quanto cada funcionário gasta atualmente com transporte e os três destinos de menor custo
"""

import pandas as pd
import googlemaps
import xlsxwriter
import requests
import re
import urllib
import urllib.request as ur
from unidecode import unidecode
from datetime import datetime
from collections import OrderedDict
from operator import getitem
from google.colab import drive
import time

drive.mount('/content/drive')

def get_distance(origin, destiny, key):
    destiny_encoded = urllib.parse.quote(destiny, safe='')
    origin_encoded = urllib.parse.quote(origin, safe='')
    route = "https://dev.virtualearth.net/REST/V1/Routes/Driving?wp.0=" + origin_encoded + "&wp.1=" + destiny_encoded + "/&key=" + key
    r = requests.get(url=route)
    result = r.json()
    print(result)
    if 'errorDetails' in result:
        distance = 1
    else:
        distance = float(result["resourceSets"][0]["resources"][0]["travelDistance"])
    return distance

def remove_non_ascii(text):
    return unidecode(text)

def web_search(search_string):
    search_string = search_string.split(' ')
    search_string = '+'.join(search_string)
    yahoo_search = 'https://br.search.yahoo.com/search?p=' + search_string
    try:
        source = ur.urlopen(yahoo_search)
        source = source.read()
        source = str(source)
        output = re.findall(r'''(?:https://|www.)[^"]+''', source)
        results = []
        for i in range(len(output)):
            if 'moovitapp.com' in output[i]:
                results.append(output[i])
        return results
    except urllib.error.URLError as e:
        print(yahoo_search)
        return []

def find_tax(url):
    page = requests.get(url).text
    pos = page.find('R$')
    if pos != -1:
        raw = page[pos + 2:pos + 8].replace(',', '.').strip()
        tax = ''
        for c in raw:
            if c in '0123456789.':
                tax += c
        if tax != '' and tax[-1] in '0123456789':
            tax = tax
        else:
            tax = tax[:len(tax) - 1]
        if tax != '' and tax[0] == '0':
            tax = '0'
        if tax == '':
            tax = '0'
        return tax
    else:
        return '0'

path_ = '/content/drive/My Drive/Hawk/Trabalhos/WorkplaceOptimization/'

#                             |--------- Google Maps API key ---------|
gmaps = googlemaps.Client(key='AIzaSyD-cV9WbzfDeY1DTxsFifqOAT284wlW7Bs')

virtual_earth_key = "AnnTANMfMLgaz5_Q2cQ-UMtVEnNdYzf5RTq0QAt0wyA1p1XFlA7xeg_Yn6pgjcE0"

employees_file = path_ + 'data/Brasanitas_Tabela_Enderecos.xlsx'  # tabela com os endereços dos funcionários e dos seus locais de trabalho
branches_file = path_ + 'data/Brasanitas_Endereco_Filiais.xlsx'   # tabela com os endereços de todas a filiais
lines_tax_file = path_ + 'results/linhas_tarifas.xlsx'  # tabela com os nomes das linhas e suas tarifas

employees_df = pd.read_excel(employees_file)
branches_df = pd.read_excel(branches_file)
lines_tax_df = pd.read_excel(lines_tax_file)

departure = datetime(2022, 10, 17, 7, 0)  # 22/09/2022 08h00
dep_ts = int(round(departure.timestamp()))

regress = datetime(2022, 10, 17, 17, 0)  # 22/09/2022 17h00
reg_ts = int(round(regress.timestamp()))

cur_cost = {}
best_cost = {}
# print('LINHAS QUE NÃO ESTÃO NA TABELA')
distance0 = 0
search_counter = 0
# percorre cada empregado
for idx_e, plan_e in employees_df.iterrows():
    cost = 0.0
    origin = str(plan_e['Endereço']) + ', ' + str(plan_e['Num.Endereço']) + ', ' + str(plan_e['Bairro']) + ', ' + str(plan_e['Municipio']) + ', ' + str(plan_e['Estado']) + ', ' + plan_e['Cep'] + ', Brasil'

    # Calcular o custo atual
    destiny = plan_e['ENDEREÇO2'] + ', ' + plan_e['BAIRRO2'] + ', ' + plan_e['MUNICIPIO2'] + ', ' + plan_e['ESTADO2'] + ', ' + plan_e['CEP2'] + ', Brasil'

    try:
        # ida
        directions_result = gmaps.directions(origin, destiny, mode='transit', departure_time=dep_ts)
        if len(directions_result) != 0:
            steps = directions_result[0]['legs'][0]['steps']
            # percorre as linhas
            for i in range(len(steps)):
                if 'transit_details' in steps[i]:
                    # nome da linha
                    line = steps[i]['transit_details']['line']
                    line_name = line['name']
                    if 'short_name' in line:
                        line_name = line['short_name'] + ' ' + line_name

                    match = False
                    for idx_lt, plan_lt in lines_tax_df.iterrows():
                        if line_name == plan_lt['LINHA']:
                            cost += plan_lt['TARIFA']
                            match = True
                            break

                    # se não encontrar a linha na tabela, procurar no Moovit
                    if not match:
                        print(line_name)
                        query_ = line_name + ' R$ moovitapp'
                        query_ = remove_non_ascii(query_)
                        query_ = re.sub('[()?.!/;:<>@#%&*_+=]', '', query_)
                        tax_ = 0.0
                        urls = web_search(query_)
                        for url_ in urls:
                            if 'pdf' in url_ or 'span' in url_:
                                continue
                            tax_ = find_tax(url_)
                            if tax_ != '0':
                                break
                            elif 'Linha' in line_name:  # é metro
                                tax_ = '4.40'
                            time.sleep(20)
                        cost += float(tax_)
                        print(float(tax_))
                        search_counter += 1
                        if search_counter == 428:
                            search_counter = 0
                            time.sleep(20)
        # volta
        directions_result = gmaps.directions(destiny, origin, mode='transit', departure_time=reg_ts)
        if len(directions_result) != 0:
            steps = directions_result[0]['legs'][0]['steps']
            # percorre as linhas
            for i in range(len(steps)):
                if 'transit_details' in steps[i]:
                    # nome da linha
                    line = steps[i]['transit_details']['line']
                    line_name = line['name']
                    if 'short_name' in line:
                        line_name = line['short_name'] + ' ' + line_name

                    match = False
                    for idx_lt, plan_lt in lines_tax_df.iterrows():
                        if line_name == plan_lt['LINHA']:
                            cost += plan_lt['TARIFA']
                            match = True
                            break

                    # se não encontrar a linha na tabela, procurar no Moovit
                    if not match:
                        print(line_name)
                        query_ = line_name + ' R$ moovitapp'
                        query_ = remove_non_ascii(query_)
                        query_ = re.sub('[()?.!/;:<>@#%&*_+=]', '', query_)
                        tax_ = 0.0
                        urls = web_search(query_)
                        for url_ in urls:
                            if 'pdf' in url_ or 'span' in url_:
                                continue
                            tax_ = find_tax(url_)
                            if tax_ != '0':
                                break
                            elif 'Linha' in line_name:  # é metro
                                tax_ = '4.40'
                            time.sleep(20)
                        cost += float(tax_)
                        print(float(tax_))
                        search_counter += 1
                        if search_counter == 428:
                            search_counter = 0
                            time.sleep(20)

        # distance0 = get_distance(origin, destiny, virtual_earth_key)
        try:
            distance0 = directions_result[0]['legs'][0]['distance']['value'] / 1000
        except:
            distance0 = 1
        cur_cost[str(plan_e['ID'])] = {}
        cur_cost[str(plan_e['ID'])]['ID_FUNC'] = plan_e['ID']
        cur_cost[str(plan_e['ID'])]['END FUNC'] = origin
        cur_cost[str(plan_e['ID'])]['ID FILIAL - 0'] = plan_e['FILIAL']
        cur_cost[str(plan_e['ID'])]['END FILIAL - 0'] = destiny
        cur_cost[str(plan_e['ID'])]['DIST - 0'] = distance0
        cur_cost[str(plan_e['ID'])]['CUSTO - 0'] = cost
    except googlemaps.exceptions.ApiError:
        print("Não encontrou no Google Maps")
        print('Origin:', origin)
        print('Destiny:', destiny)
        print('  ')

    # Calcular os três melhores custos
    # percorrer cada filial
    branches_cost = {}
    for idx_b, plan_b in branches_df.iterrows():
        cost = 0.0
        destiny = plan_b['ENDERECO'] + ', ' + plan_b['BAIRRO'] + ', ' + plan_b['MUNICIPIO'] + ', ' + plan_b['ESTADO'] + ', ' + plan_b['CEP'] + ', Brasil'
        try:
            # ida
            directions_result = gmaps.directions(origin, destiny, mode='transit', departure_time=dep_ts)
            if len(directions_result) != 0:
                steps = directions_result[0]['legs'][0]['steps']
                for i in range(len(steps)):
                    if 'transit_details' in steps[i]:
                        line = steps[i]['transit_details']['line']
                        line_name = line['name']
                        if 'short_name' in line:
                            line_name = line['short_name'] + ' ' + line_name

                        match = False
                        for idx_lt, plan_lt in lines_tax_df.iterrows():
                            if line_name == plan_lt['LINHA']:
                                cost += plan_lt['TARIFA']
                                match = True
                                break

                        # se não encontrar a linha na tabela, procurar no Moovit
                        if not match:
                            query_ = line_name + ' R$ moovitapp'
                            query_ = remove_non_ascii(query_)
                            tax_ = 0.0
                            urls = web_search(query_)
                            for url_ in urls:
                                if 'pdf' in url_ or 'span' in url_:
                                    continue
                                tax_ = find_tax(url_)
                                if tax_ != '0':
                                    break
                                elif 'Linha' in line_name:  # é metrô
                                    tax_ = '4.40'
                                time.sleep(20)
                            cost += float(tax_)
                            # print(float(tax_))
                            search_counter += 1
                            if search_counter == 428:
                                search_counter = 0
                                time.sleep(20)
            # volta
            directions_result = gmaps.directions(destiny, origin, mode='transit', departure_time=reg_ts)
            if len(directions_result) != 0:
                steps = directions_result[0]['legs'][0]['steps']
                for i in range(len(steps)):
                    if 'transit_details' in steps[i]:
                        line = steps[i]['transit_details']['line']
                        line_name = line['name']
                        if 'short_name' in line:
                            line_name = line['short_name'] + ' ' + line_name

                        match = False
                        for idx_lt, plan_lt in lines_tax_df.iterrows():
                            if line_name == plan_lt['LINHA']:
                                cost += plan_lt['TARIFA']
                                match = True
                                break

                        # se não encontrar a linha na tabela, procurar no Moovit
                        if not match:
                            query_ = line_name + ' R$ moovitapp'
                            query_ = remove_non_ascii(query_)
                            tax_ = 0.0
                            urls = web_search(query_)
                            for url_ in urls:
                                if 'pdf' in url_ or 'span' in url_:
                                    continue
                                tax_ = find_tax(url_)
                                if tax_ != '0':
                                    break
                                elif 'Linha' in plan_lt['LINHA']:  # é metro
                                    tax_ = '4.40'
                                time.sleep(20)
                            cost += float(tax_)
                            # print(float(tax_))
                            search_counter += 1
                            if search_counter == 428:
                                search_counter = 0
                                time.sleep(20)
            # distance = get_distance(origin, destiny, virtual_earth_key)
            try:
                distance = directions_result[0]['legs'][0]['distance']['value'] / 1000
            except:
                distance = 1
            branches_cost[str(plan_b['ID_FILIAL'])] = {}
            branches_cost[str(plan_b['ID_FILIAL'])]['ID FILIAL'] = plan_b['ID_FILIAL']
            branches_cost[str(plan_b['ID_FILIAL'])]['END FILIAL'] = destiny
            branches_cost[str(plan_b['ID_FILIAL'])]['DIST'] = distance
            branches_cost[str(plan_b['ID_FILIAL'])]['CUSTO'] = cost
            branches_cost[str(plan_b['ID_FILIAL'])]['D/D0'] = 100.0 - (100.0 * distance / distance0)
        except googlemaps.exceptions.ApiError:
            print("Not found")
            print('Origin:', origin)
            print('Destiny:', destiny)
            print('  ')

    # ordenar dicionário de custo por filial e selecionar os três menores
    branches_cost = OrderedDict(sorted(branches_cost.items(), key = lambda item: getitem(item[1], 'CUSTO')))
    best_cost[str(plan_e['ID'])] = dict(list(branches_cost.items())[:3])  # se quiser aumentar ou diminuir o número de filiais candidatas, mudar esse número [:3]

row = 0
col = 0
workbook = xlsxwriter.Workbook(path_ + 'results/custo_atual_e_3melhores.xlsx')
worksheet = workbook.add_worksheet()
worksheet.write(row, col, 'ID_FUNC')
worksheet.write(row, col + 1, 'END FUNC')
worksheet.write(row, col + 2, 'ID FILIAL - 0')
worksheet.write(row, col + 3, 'END FILIAL - 0')
worksheet.write(row, col + 4, 'DIST - 0')
worksheet.write(row, col + 5, 'CUSTO - 0')
worksheet.write(row, col + 6, 'ID FILIAL - 1')
worksheet.write(row, col + 7, 'END FILIAL - 1')
worksheet.write(row, col + 8, 'DIST - 1')
worksheet.write(row, col + 9, 'CUSTO - 1')
worksheet.write(row, col + 10, '% D1 / D0')
worksheet.write(row, col + 11, 'ID FILIAL - 2')
worksheet.write(row, col + 12, 'END FILIAL - 2')
worksheet.write(row, col + 13, 'DIST - 2')
worksheet.write(row, col + 14, 'CUSTO - 2')
worksheet.write(row, col + 15, '% D2 / D0')
worksheet.write(row, col + 16, 'ID FILIAL - 3')
worksheet.write(row, col + 17, 'END FILIAL - 3')
worksheet.write(row, col + 18, 'DIST - 3')
worksheet.write(row, col + 19, 'CUSTO - 3')
worksheet.write(row, col + 20, '% D3 / D0')
row += 1
cur_keys = cur_cost.keys()
for key in cur_keys:
    # informações da rota atual
    worksheet.write(row, col, cur_cost[key]['ID_FUNC'])
    worksheet.write(row, col + 1, cur_cost[key]['END FUNC'])
    worksheet.write(row, col + 2, cur_cost[key]['ID FILIAL - 0'])
    worksheet.write(row, col + 3, cur_cost[key]['END FILIAL - 0'])
    worksheet.write(row, col + 4, cur_cost[key]['DIST - 0'])
    worksheet.write(row, col + 5, cur_cost[key]['CUSTO - 0'])

    branches = best_cost[key]
    branches_keys = list(branches.keys())
    # informações da primeira sugestão
    worksheet.write(row, col + 6, branches[branches_keys[0]]['ID FILIAL'])
    worksheet.write(row, col + 7, branches[branches_keys[0]]['END FILIAL'])
    worksheet.write(row, col + 8, branches[branches_keys[0]]['DIST'])
    worksheet.write(row, col + 9, branches[branches_keys[0]]['CUSTO'])
    worksheet.write(row, col + 10, branches[branches_keys[0]]['D/D0'])

    # informações da segunda sugestão
    worksheet.write(row, col + 11, branches[branches_keys[1]]['ID FILIAL'])
    worksheet.write(row, col + 12, branches[branches_keys[1]]['END FILIAL'])
    worksheet.write(row, col + 13, branches[branches_keys[1]]['DIST'])
    worksheet.write(row, col + 14, branches[branches_keys[1]]['CUSTO'])
    worksheet.write(row, col + 15, branches[branches_keys[1]]['D/D0'])

    # informações da terceira sugestão
    worksheet.write(row, col + 16, branches[branches_keys[2]]['ID FILIAL'])
    worksheet.write(row, col + 17, branches[branches_keys[2]]['END FILIAL'])
    worksheet.write(row, col + 18, branches[branches_keys[2]]['DIST'])
    worksheet.write(row, col + 19, branches[branches_keys[2]]['CUSTO'])
    worksheet.write(row, col + 20, branches[branches_keys[2]]['D/D0'])

    row += 1
workbook.close()